# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# YAML guide
# https://stackoverflow.com/a/21699210/4729477
#
########################################
title:        Gunawan Wijaya
email:        gunawan@wijaya.cc
description:  |
  Hi there, my name is Gunawan, spelled goo - nah - one.
  I do many things, from Front End to Big Spoon.
baseurl:      "" # the subpath of your site, e.g. /blog
url:          https://gunawan.wijaya.cc # the base hostname & protocol for your site, e.g. http://example.com
copyright:    <https://wijaya.cc/> © 2017
repository:   gunawanwijaya/gunawanwijaya.github.io
########################################
analytics:
  google:     UA-67065348-1
  mixpanel:   8104be8963c319b2d6aef0fd2da80da3
  yandex:     44827765
disqus:
  shortname:  wijaya-cc
########################################
limit_posts:  12
permalink:    pretty
show_drafts:  false
unpublished:  false
future:       false
########################################
defaults:
  - ####################################
    scope:
      path:   ""
    values:
      layout: page
      author: Gunawan Wijaya
  - ####################################
    scope: { path: _posts }
    values: { layout: post }
  - ####################################
    scope: { path: _drafts }
    values: { layout: post }
########################################
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
########################################
sass:
  style: compressed
########################################
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
########################################
exclude:
  - Gemfile
  - Gemfile.lock
########################################
